jaredsburrows/gradle-license-plugin

- src/main/groovy/com/jaredsburrows/license/LicenseReportTask.groovy
- src/test/resources/maven/group/grandparent/1.0.0/grandparent-1.0.0.pom
> issue #26 Recursively scan parent POMs for license

- README.md
- src/main/groovy/com/jaredsburrows/license/AndroidLicenseReportOptions.groovy
- src/main/groovy/com/jaredsburrows/license/LicensePlugin.groovy
- src/main/groovy/com/jaredsburrows/license/LicenseReportOptions.groovy
- src/main/groovy/com/jaredsburrows/license/LicenseReportTask.groovy
- src/test/groovy/com/jaredsburrows/license/LicenseReportTaskAndroidSpec.groovy
Added configuration options to allow scripts to configure the following properties in Android projects:
- Enable/disable HTML report generation
- Enable/disable HTML report copying to assets
- Enable/disable JSON report generation
- Enable/disable JSON report copying to assets
Added tests to check that options are used by task.
> Added configuration options

- README.md
- src/main/groovy/com/jaredsburrows/license/LicenseReportTask.groovy
- src/main/groovy/com/jaredsburrows/license/internal/pom/Project.groovy
- src/main/groovy/com/jaredsburrows/license/internal/report/HtmlReport.groovy
- src/main/groovy/com/jaredsburrows/license/internal/report/JsonReport.groovy
- src/test/groovy/com/jaredsburrows/license/LicenseReportTaskAndroidSpec.groovy
- src/test/groovy/com/jaredsburrows/license/LicenseReportTaskJavaSpec.groovy
- src/test/groovy/com/jaredsburrows/license/internal/report/HtmlReportSpec.groovy
- src/test/groovy/com/jaredsburrows/license/internal/report/JsonReportSpec.groovy
I needed to add some extra info into the JSON report for my own purposes. If you feel this is useful for others too, then please consider merging.
There are two related changes here:
1. Add dependencies for which no licenses were found into the reports, with an empty licenses array in the JSON report. The HTML report adds dependencies with no licenses in a "no licenses found" section.
2. Add the original gradle dependency string (group:name:version string) into the JSON report - makes it easier to track down a dependency if the description is not enough.
> Extra report info

- src/main/groovy/com/jaredsburrows/license/internal/report/HtmlReport.groovy
- src/test/groovy/com/jaredsburrows/license/LicenseReportTaskAndroidSpec.groovy
- src/test/groovy/com/jaredsburrows/license/LicenseReportTaskJavaSpec.groovy
- src/test/groovy/com/jaredsburrows/license/internal/report/HtmlReportSpec.groovy
This simply surrounds any links to license text with `<a href></a>` so that the user can click on them to follow the link and read the license.
> make any links to licenses clickable in preformatted text

- README.md
- build.gradle
- gradle/dependencies.gradle
- src/main/kotlin/com/jaredsburrows/license/internal/report/JsonReport.kt
- src/test/groovy/com/jaredsburrows/license/LicensePluginAndroidSpec.groovy
- src/test/groovy/com/jaredsburrows/license/LicensePluginJavaSpec.groovy
- src/test/groovy/com/jaredsburrows/license/internal/pom/DeveloperSpec.groovy
- src/test/groovy/com/jaredsburrows/license/internal/pom/LicenseSpec.groovy
- src/test/groovy/com/jaredsburrows/license/internal/pom/ProjectSpec.groovy
- src/test/groovy/com/jaredsburrows/license/internal/report/HtmlReportSpec.groovy
- src/test/groovy/com/jaredsburrows/license/internal/report/JsonReportSpec.groovy
- src/test/groovy/test/TestUtils.groovy
- Fix HTML and JSON indentation in tests
- Fix HTML output
- 2 space indent
- Use of `"` instead of `'`
- Fix JSON output
- 2 space indent
- Remove `trim()` and `stripIndent()`
- Compare JSON and HTML by validating and comparing the data and not the format
> Use Gson for Json

- src/main/kotlin/com/jaredsburrows/license/internal/LicenseHelper.kt
You asked that the additional spelling of the MIT License (.php extension) be a separate pull request, so here it is. I ran across this in an actual library I'm using. It's a one-line addition.
> Add another official spelling of the MIT License URL.

- src/main/kotlin/com/jaredsburrows/license/LicenseReportTask.kt
- src/test/groovy/com/jaredsburrows/license/LicensePluginAndroidSpec.groovy
For some reason dependencies that come from android library subproject were not collected. There must be something different between` java-library` and `com.android.library` plugins. I observed though that all the dependencies can be found in `xxxRuntimeClasspath` configuration so I used that one instead.
This works for my setup and for all the existing tests. But gradle dependency resolution is not my area of expertise so I would appreciate a review of this change.
> Add android library subproject dependencies to the report

- src/main/kotlin/com/jaredsburrows/license/LicenseReportTask.kt
- src/test/groovy/com/jaredsburrows/license/LicensePluginAndroidSpec.groovy
Starting with the Android gradle plugin `com.android.tools.build:gradle` version `7.1.0` the dependency resolution changed and therefore different dependency types like '.aar' appear within the list of resolved artifacts/dependencies.
These types have to be excluded before parsing a dependency to avoid failures.
Currently .aar dependencies will cause following error:
```
> Task :app:licenseReleaseReport
circularimageview dependency does not have a license.
[Fatal Error] vectordrawable-animated-1.1.0.aar:1:1: Content is not allowed in prolog.
> Task :app:licenseReleaseReport FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:licenseReleaseReport'.
> org.xml.sax.SAXParseException; systemId: …
```
> Avoid processing *.aar dependencies which can not be parsed and cause gradle failures

- README.md
copyHtmlReportToAssets was twice in the example configuration
> Fix copyCsvReportToAssets in README.md

- src/main/kotlin/com/jaredsburrows/license/LicenseReportTask.kt
Currently running the license report task in multi-project setups is frequently causing the task to fail with "FWK005 parse may not be called while parsing." This is caused by the fact that LicenseReportTask.kt uses a static (companion) parser object. If parsing is already in progress for one project, a second report task on another project will fail if it tries to parse at the same time. This can be resolved by using an instance local parser variable.
> Fix license report task in multi-project setups

- src/main/kotlin/com/jaredsburrows/license/projectJava.kt
- src/test/groovy/com/jaredsburrows/license/LicensePluginAndroidSpec.groovy
- src/test/groovy/com/jaredsburrows/license/LicensePluginJavaSpec.groovy
- src/test/groovy/com/jaredsburrows/license/LicensePluginSpec.groovy
- src/test/groovy/com/jaredsburrows/license/internal/report/HtmlReportSpec.groovy
- src/test/groovy/test/TestUtils.groovy
- Update Java Plugin detection
- Fix formatting in tests
- Add more plugin validation tests
> add more tests

- .gitignore
- README.md
- gradle-license-plugin/src/main/kotlin/com/jaredsburrows/license/internal/report/HtmlReport.kt
- gradle-license-plugin/src/test/groovy/com/jaredsburrows/license/LicensePluginAndroidSpec.groovy
- gradle-license-plugin/src/test/groovy/com/jaredsburrows/license/LicensePluginJavaSpec.groovy
- gradle-license-plugin/src/test/groovy/com/jaredsburrows/license/internal/report/HtmlReportSpec.groovy
This is a duplicate PR of #101. The old PR is abandoned and has conflicts, thus creating a new one.
This work was originally done by  @kgbier
TODO:
> Update html css to support word-breaking on long lines

- gradle-license-plugin/src/main/kotlin/com/jaredsburrows/license/internal/report/CsvReport.kt
- gradle-license-plugin/src/test/groovy/com/jaredsburrows/license/internal/report/CsvReportSpec.groovy
instead of having "null" in your csv an empty string makes more sense
this fixes #246
> CsvReport: missing values converted to empty strings

- gradle-license-plugin/src/main/kotlin/com/jaredsburrows/license/internal/report/CsvReport.kt
- gradle-license-plugin/src/test/groovy/com/jaredsburrows/license/internal/report/CsvReportSpec.groovy
the default escape character for CSV is " which has to be escaped with a double ""
Additionally, when a column contains any of these character it has to be put inside quotes:
- " (double quote)
- , (comma)
- ' (single quote)
- \ (backslash)
- \n (new line)
This should fix #223
> CsvReport: escape special characters

- gradle-license-plugin/src/main/kotlin/com/jaredsburrows/license/LicenseReportTask.kt
- gradle-license-plugin/src/test/groovy/com/jaredsburrows/license/LicensePluginJavaSpec.groovy
Addresses issue #394.
This PR improves the performance of `getResolvedArtifactsFromResolvedDependencies` by recording the dependencies that have already been processed.
This allows the function that used to take exponential time in the worst case to now be done in linear time.
The test I wrote takes about 2 minutes on my machine before the patch is applied, but now takes only a few seconds after the patch is applied.
> Fix exponential execution time for resolving complex dependencies

- gradle-license-plugin/src/main/kotlin/com/jaredsburrows/license/internal/LicenseHelper.kt
This PR adds entries into `licenseMap` to enable grouping licenses defined by slightly different names or URLs.
These entries are taken from real-word examples, and exclude ambiguous names and unofficial URLs.
More information can be found in #395.
> Enhance known licenses list

- build.gradle
- gradle-license-plugin/src/main/kotlin/com/jaredsburrows/license/internal/ConsoleRenderer.kt
- gradle-license-plugin/src/main/kotlin/com/jaredsburrows/license/internal/report/HtmlReport.kt
- gradle-license-plugin/src/test/groovy/com/jaredsburrows/license/LicensePluginAndroidSpec.groovy
- gradle-license-plugin/src/test/groovy/com/jaredsburrows/license/LicensePluginJavaSpec.groovy
- gradle-license-plugin/src/test/groovy/com/jaredsburrows/license/internal/report/HtmlReportSpec.groovy
- gradle-license-plugin/src/test/groovy/test/TestUtils.groovy
- gradle/libs.versions.toml
Validate and fix HTML errors - https://validator.w3.org/#validate_by_input
- Trailing slash on void elements [has no effect](https://github.com/validator/validator/wiki/Markup-%C2%BB-Void-elements#trailing-slashes-in-void-element-start-tags-do-not-mark-the-start-tags-as-self-closing) and [interacts badly with unquoted attribute values](https://github.com/validator/validator/wiki/Markup-%C2%BB-Void-elements#trailing-slashes-directly-preceded-by-unquoted-attribute-values).
- Element [dl](https://html.spec.whatwg.org/multipage/#the-dl-element) is missing a required instance of child element dd.
- The name attribute is obsolete. Consider putting an id attribute on the nearest container instead.
- Element [pre](https://html.spec.whatwg.org/multipage/#the-pre-element) not allowed as child of …
> validate html

- README.md
Closes https://github.com/jaredsburrows/gradle-license-plugin/issues/299
> update dialog code

- gradle-license-plugin/src/main/kotlin/com/jaredsburrows/license/internal/report/HtmlReport.kt
- gradle-license-plugin/src/test/groovy/com/jaredsburrows/license/internal/report/HtmlReportSpec.groovy
Closes https://github.com/jaredsburrows/gradle-license-plugin/issues/409.
This PR introduces the stable order of project groups in HTML report.
It makes it less likely that changes in dependencies will result in large diffs of output.
Project groups are sorted by their respective license keys.
A real-world example will looks like this:
```
(no licenses)
[apache-2.0.txt, https://github.com/facebook/facebook-android-sdk/blob/main/LICENSE.txt, https://www.facebook.com/legal/audience_network_beta_sdk_terms]
[apache-2.0.txt]
[bsd-2-clause.txt]
[bsd-3-clause.txt]
[epl-2.0.txt]
[https://developer.android.com/guide/playcore/license]
[https://developer.android.com/studio/terms.html]
[https://github.com/facebook/facebook-android-sdk/blob/main/LICENSE.txt]
[mit.txt]
```
> Sort project group order in HTML report using license keys

- gradle-license-plugin/src/main/kotlin/com/jaredsburrows/license/internal/report/HtmlReport.kt
- gradle-license-plugin/src/test/groovy/com/jaredsburrows/license/LicensePluginAndroidSpec.groovy
- gradle-license-plugin/src/test/groovy/com/jaredsburrows/license/LicensePluginJavaSpec.groovy
- gradle-license-plugin/src/test/groovy/com/jaredsburrows/license/internal/report/HtmlReportSpec.groovy
Closes #457 
Validated by: https://validator.w3.org/nu/#textarea
<details close>
<summary>Sample HTML</summary>
<br>
```
<!DOCTYPE html>
<html lang="en">
<head><meta http-equiv="content-type" content="text/html; charset=utf-8">
<style>
body {
font-family: sans-serif;
background-color: #ffffff; /* Light background */
color: #000000; /* Dark text */
}
a {
color: #0000EE; /* Default blue for links */
}
pre {
background-color: #eeeeee; /* Lighter background for preformatted text */
color: #000000; /* Dark text for readability */
}
@media (prefers-color-scheme: dark) {
body {
background-color: #121212; /* Dark background */
color: #E0E0E0; /* Light text */
}
a {
color: #BB86FC; /* Light purple for links */
}
pre {
background-color: #333333; /* Darker background for preformatted text */
color: …
```
> Add dark mode support for html

- gradle-license-plugin/src/test/groovy/com/jaredsburrows/license/LicensePluginJavaSpec.groovy
Both https://github.com/jaredsburrows/gradle-license-plugin/pull/464 and https://github.com/jaredsburrows/gradle-license-plugin/pull/465 passed the build. Both were merged at the same time, breaking the build.
> fix wrong css

- gradle-license-plugin/src/main/kotlin/com/jaredsburrows/license/LicenseReportTask.kt
- gradle-license-plugin/src/test/groovy/com/jaredsburrows/license/LicensePluginAndroidSpec.groovy
- gradle-license-plugin/src/test/groovy/com/jaredsburrows/license/LicensePluginJavaSpec.groovy
- gradle-license-plugin/src/test/resources/maven/group/module-same-name-1/1.0.0/module-same-name-1-1.0.0.pom
- gradle-license-plugin/src/test/resources/maven/group/module-same-name-2/1.0.0/module-same-name-2-1.0.0.pom
Fixes https://github.com/jaredsburrows/gradle-license-plugin/issues/491
In some rare cases, the package name in the POM is the same for multiple dependencies, and for some reason those kind of dependencies are sorted non-deterministically.
This PR should stabilize the order of the dependencies by using the dependency id (group:module:version) as fallback, which is supposed to be universally unique.
> Make sure dependencies are sorted deterministically
