README.md
src/main/groovy/com/jaredsburrows/license/internal/LicenseHelper.groovy
src/main/groovy/com/jaredsburrows/license/internal/report/HtmlReport.groovy
src/main/resources/license/apache-2.0.txt
src/main/resources/license/bsd-2-clause.txt
src/main/resources/license/bsd-3-clause.txt
src/main/resources/license/epl-2.0.txt
src/main/resources/license/gpl-2.0.txt
src/main/resources/license/gpl-3.0.txt
src/main/resources/license/lgpl-2.1.txt
src/main/resources/license/lgpl-3.0.txt
src/main/resources/license/mit.txt
src/main/resources/license/mpl-2.0.txt
src/test/groovy/com/jaredsburrows/license/LicenseReportTaskAndroidSpec.groovy
src/test/groovy/com/jaredsburrows/license/LicenseReportTaskJavaSpec.groovy
src/test/groovy/com/jaredsburrows/license/internal/report/HtmlReportSpec.groovy
src/test/groovy/com/jaredsburrows/license/internal/report/JsonReportSpec.groovy
src/test/groovy/test/BaseJavaSpecification.groovy

Closes https://github.com/jaredsburrows/gradle-license-plugin/issues/24

Map packages to Full license text

---

src/main/groovy/com/jaredsburrows/license/LicenseReportTask.groovy
src/main/groovy/com/jaredsburrows/license/internal/report/HtmlReport.groovy
src/test/groovy/com/jaredsburrows/license/LicensePluginAndroidSpec.groovy
src/test/groovy/com/jaredsburrows/license/LicensePluginJavaSpec.groovy

#69 - remove undesired captilization

---

src/main/groovy/com/jaredsburrows/license/LicenseReportTask.groovy
src/main/kotlin/com/jaredsburrows/license/LicenseReportTaskKt.kt
src/test/groovy/com/jaredsburrows/license/LicensePluginAndroidSpec.groovy

#55 - fix crash when having multiple variants or running 'gradlew build'

---

src/main/groovy/com/jaredsburrows/license/LicenseReportTask.groovy
src/main/kotlin/com/jaredsburrows/license/LicenseReportTaskKt.kt
src/test/groovy/com/jaredsburrows/license/LicensePluginJavaSpec.groovy

#48 - fix null version for parent dependencies

---

src/main/kotlin/com/jaredsburrows/license/LicenseReportTask.kt
src/main/kotlin/com/jaredsburrows/license/internal/ConsoleRenderer.kt

Similar to https://github.com/jaredsburrows/gradle-spoon-plugin/pull/54.

consoler renderer

---

src/main/kotlin/com/jaredsburrows/license/internal/report/HtmlReport.kt

#110 - fix windows file path

---

README.md

Reverts jaredsburrows/gradle-license-plugin#124

Revert "Updated the readme version"

---

src/main/kotlin/com/jaredsburrows/license/LicensePlugin.kt

Remove instant app plugin, support feature, library and application

---

README.md

#129 - update readme to include correct maven repositories

---

README.md
build.gradle
gradle/dependencies.gradle
gradle/wrapper/gradle-wrapper.properties
src/main/kotlin/com/jaredsburrows/license/LicensePlugin.kt
src/main/kotlin/com/jaredsburrows/license/LicenseReportExtension.kt
src/main/kotlin/com/jaredsburrows/license/LicenseReportTask.kt
src/main/kotlin/com/jaredsburrows/license/internal/report/CsvReport.kt
src/main/kotlin/com/jaredsburrows/license/internal/report/HtmlReport.kt
src/main/kotlin/com/jaredsburrows/license/internal/report/JsonReport.kt
src/main/kotlin/com/jaredsburrows/license/internal/report/Report.kt
src/test/groovy/com/jaredsburrows/license/LicensePluginAndroidSpec.groovy
src/test/groovy/com/jaredsburrows/license/LicensePluginJavaSpec.groovy
src/test/groovy/com/jaredsburrows/license/internal/report/CsvReportSpec.groovy
src/test/groovy/com/jaredsburrows/license/internal/report/JsonReportSpec.groovy
src/test/groovy/test/TestUtils.groovy

Add CSV Reports

---

src/main/kotlin/com/jaredsburrows/license/LicenseReportTask.kt

Closes https://github.com/jaredsburrows/gradle-license-plugin/issues/143
@sergeys-opera

Remove upToDateWhen in favor of Gradle annotations

---

README.md
build.gradle
src/main/kotlin/com/jaredsburrows/license/LicensePlugin.kt
src/main/kotlin/com/jaredsburrows/license/projectAndroid.kt
src/main/kotlin/com/jaredsburrows/license/projectJava.kt

compile only agp

---

src/main/kotlin/com/jaredsburrows/license/internal/report/HtmlReport.kt
src/test/groovy/com/jaredsburrows/license/LicensePluginAndroidSpec.groovy
src/test/groovy/com/jaredsburrows/license/LicensePluginJavaSpec.groovy
src/test/groovy/com/jaredsburrows/license/LicensePluginSpec.groovy
src/test/groovy/com/jaredsburrows/license/internal/report/HtmlReportSpec.groovy

- Add doctype - `<!DOCTYPE html>`
- Add META - `<meta http-equiv="content-type" content="text/html; charset=utf-8" />`
- Add `lang` to `html` tag - `lang="en"`

Add doctype, META and lang to HTML

---

README.md
src/main/kotlin/com/jaredsburrows/license/BaseLicenseReportTask.kt
src/main/kotlin/com/jaredsburrows/license/LicenseReportExtension.kt
src/main/kotlin/com/jaredsburrows/license/LicenseReportTask.kt
src/main/kotlin/com/jaredsburrows/license/internal/report/TextReport.kt
src/test/groovy/com/jaredsburrows/license/LicensePluginAndroidSpec.groovy
src/test/groovy/com/jaredsburrows/license/LicensePluginJavaSpec.groovy
src/test/groovy/com/jaredsburrows/license/LicensePluginVersionSpec.groovy
src/test/groovy/com/jaredsburrows/license/internal/report/TextReportSpec.groovy
src/test/groovy/test/TestUtils.groovy

generate text report

---

src/main/kotlin/com/jaredsburrows/license/LicenseReportTask.kt
src/test/groovy/com/jaredsburrows/license/LicensePluginAndroidSpec.groovy
src/test/groovy/com/jaredsburrows/license/LicensePluginJavaSpec.groovy

- Use more Kotlin language features
- Update tests to make sure files are written
- Update logging

more kotlin

---

build.gradle
gradle/dependencies.gradle
src/main/kotlin/com/jaredsburrows/license/LicenseReportTask.kt

- Use Maven Reader
- Remove dependency on Groovy

use maven parser

---

README.md
gradle-license-plugin/src/main/kotlin/com/jaredsburrows/license/LicenseReportExtension.kt
gradle-license-plugin/src/main/kotlin/com/jaredsburrows/license/LicenseReportTask.kt
gradle-license-plugin/src/main/kotlin/com/jaredsburrows/license/project.kt
gradle-license-plugin/src/test/groovy/com/jaredsburrows/license/LicensePluginAndroidSpec.groovy

* Checks each full artifact specifier for the given patterns
via simple contains condition and ignores if a match is found.
* Adapted and added tests.
* Updated README.md.

Replaced ignoredGroups with ignoredPatterns

---

gradle-license-plugin/src/main/kotlin/com/jaredsburrows/license/LicenseReportTask.kt
gradle-license-plugin/src/test/groovy/com/jaredsburrows/license/LicensePluginJavaSpec.groovy
gradle-license-plugin/src/test/resources/maven/com/sun/activation/javax.activation/1.2.0/javax.activation-1.2.0.pom

Closes #275 
Similar to https://github.com/CycloneDX/cyclonedx-gradle-plugin/pull/152

fix #275 by using ReaderFactory.newXmlReader

---

gradle-license-plugin/src/main/kotlin/com/jaredsburrows/license/internal/report/HtmlReport.kt

I just realized that I left the debug print in PR #433 by mistake. 🙏 
This PR removes this line.

Remove debug print

---

README.md
gradle-license-plugin/src/main/kotlin/com/jaredsburrows/license/LicenseReportExtension.kt
gradle-license-plugin/src/main/kotlin/com/jaredsburrows/license/LicenseReportTask.kt
gradle-license-plugin/src/main/kotlin/com/jaredsburrows/license/Project.kt
gradle-license-plugin/src/main/kotlin/com/jaredsburrows/license/internal/report/HtmlReport.kt
gradle-license-plugin/src/test/groovy/com/jaredsburrows/license/LicensePluginAndroidSpec.groovy
gradle-license-plugin/src/test/groovy/com/jaredsburrows/license/LicensePluginJavaSpec.groovy
gradle-license-plugin/src/test/groovy/com/jaredsburrows/license/internal/report/HtmlReportSpec.groovy

Dont show versions in html

---

build.gradle

Closes https://github.com/jaredsburrows/gradle-license-plugin/issues/583

Remove -Xproper-ieee754-comparisons
